name: 'Build'
variables:
  build_number: '$(Build.BuildNumber)'
  commit_id: '$(Build.SourceVersion)'

trigger:
  branches:
    include:
    - '*'

stages:
- stage: Build
  displayName: 'Build stage'
jobs:
- job: Build
  timeoutInMinutes: 100
  steps:
  - task: Bash@3
    displayName: 'Test Application'
    inputs:
      targetType: inline
      script: |
          cd notejam/spring
          mvn test
  - task: CopyFiles@1
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'

      Contents: |
        **
      TargetFolder: '$(build.artifactstagingdirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: 'Build'
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
   - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: NoteJava'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
